### PR TITLE
Expand view mappings.

### PR DESCRIPTION
**Pull request by PaSaSaP**
Small change that allows to expand view mappings.

### CODE REVIEW

**Comment by p4paul** [comment]
Just wanted to confirm the issue, as the code change is quite subtle.  The only difference I can see is that you expand the variables before the for loop, instead of per line.  Is there a situation where the original code fails?  I'd like to write a test to cover the issue.

**Comment by PaSaSaP** [comment]
Hi. It is for the case when view map is exported via environment variable with ie. [https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin](url). I have also tested exporing variabled via **Groovy Script**. In my case I have used **Properties File Path** with content:
>VIEW_MAP=\\
>//depot/hdr/\* //job-name/hdr/\*\n\\
>//depot/src/\* //job-name/src/\*\n\\

And in **View Mappings** I have had:
>${VIEW_MAP}

**Comment by p4paul** [comment]
Thanks - I hadn't thought of replacing the whole map with ${VIEW_MAP}.  I can see why you would want it expanded first.

**Comment by p4paul** [comment]
Hi @PaSaSaP, 
It looks like this change may break a client view that contain unexpanded variables. I need to look at this in more depth. 
https://issues.jenkins-ci.org/browse/JENKINS-50393

**Pull request merged**
