### PR TITLE
P4_CHANGELIST documentation Upgraded

### PR DESCRIPTION
**Pull request by Mayank77maruti**
https://issues.jenkins.io/browse/JENKINS-73075

JENKINS-73075 : P4_CHANGELIST is not documented when there are no changelists in workspace

Description Of changes -> I changed the documentation of **P4_CHANGELIST**  from `The last Perforce changelist number included in the populated workspace.` to `The last Perforce changelist number included in the populated workspace, or the latest changelist number across the Perforce server if no changelist is found in the workspace.` as discussed in the issue discussion. 
This documentation also helps the users with understanding the content of P4_CHANGELIST when a workspace is not populated.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by altostratous — APPROVED** [review]
Sounds good. Thanks.

**Comment by Mayank77maruti** [comment]
Hey @skumar7322 , the changes have been approved for the following issue.
Please do review and merge.
Thank you.

**Comment by Mayank77maruti** [comment]
Hey @skumar7322 changes have been been.
Looking forward to reviews and merge.
Thank you

**Comment by skumar7322** [comment]
Thanks, @Mayank77maruti for creating this PR to improve P4Plugin. The changes looks good.

**Pull request merged**
