### PR TITLE
Implementing a Java Pattern filter for polling

### PR DESCRIPTION
**Pull request by jromigh**
The ViewMask filter leaves a LOT to be desired, especially if you want a lot of control on SCM polling such as on certain filetypes. This filter should give a large amount of control via Java regular expressions (patterns).

The only thing I couldn't figure out how to do was implement Console logging when I detected an improper Pattern from my filter class (ideally we could even catch this in the test and ensure the logging is there). Would love to hear any advice on how to accomplish that.

### CODE REVIEW

**Comment by p4paul** [comment]
Just been reviewing this with Karl in support and he referenced an older - related issue: https://issues.jenkins-ci.org/browse/JENKINS-41217
The changes look good, I'll merge them in; thank you for your help.

**Comment by jromigh** [comment]
An improvement on this would be a validation step much like the cron trigger has, though I don't know off-hand how to build that.

**Comment by p4paul** [comment]
You can add some Jelly magic (JS) to validate the regex; there are examples of this in the auto path complete for streams or client name verification.
Take a look at org.jenkinsci.plugins.p4.workspace.WorkspaceDescriptor checkClientName() or autoCompleteName().  You can add these into your own inner static class DescriptorImpl.  There is some magic (java reflections/jelly stapler) to match the method name doAutoCompleteXxx and 
doCheckXxx.
As for logging you can add to the console within PollTask by callin p4.log("..."), for logging outside of tasks use the static Logger.getLogger().

**Comment by jromigh** [comment]
Thanks for the tips! I've made another pull request to add the checks.

**Pull request merged**
