### PR TITLE
[JENKINS-35210] Fix for SECURITY-170

### PR DESCRIPTION
**Pull request by amuniz**
This PR fixes parameters visibility after SECURITY-170 inclusion in core (1.651.2 or 2.3+).
It also fixes tests failing under `mvn test -Djenkins.version=1.651.2` (due to the same issue).

@reviewbybees

### CODE REVIEW

**Comment by p4paul** [comment]
Thanks for the security fix.  Did you want to update your PR?  I just merged in PR #24, Happy to merge it in for you either way.
Kind regards,
Paul

**Comment by amuniz** [comment]
@p4paul upstream merged to fix conflicts.

**Comment by amuniz** [comment]
The build is failing because of findbugs errors. Unrelated with this PR I think.

**Comment by p4paul** [comment]
The error was a @CheckForNull in PR #24

**Pull request merged**
