### PR TITLE
Made Pin Label work when doing a Build Now task

### PR DESCRIPTION
**Pull request by Palmr**
Recently changed from the other perforce plugin to this one and couldn't get it to sync a specific label.
Saw the "Pin Build at Perforce Label" option and had no idea what that meant, but assumed it would sync on a given label. It did nothing however.

Grabbed the source and saw Populate.getPin() wasn't even referenced in CheckoutTask.java so now when calling getBuildChange() it checks for the label defined on the given populate config for the task.

As I could find no reference on "pinning" as terminology related to VCS labels (assume this is some internal Perforce nomenclature) and nobody I talked to could figure out what it meant with 100% confidence (even with the help text) I renamed the field to just "label", as that seemed to make sense to everyone in our company and matches the field in the other plugin. I could undo this however as I don't know how to make old config automatically change from pin -> label so any use of that field needs re-configuring in build tasks which is a pain for users now.

I used IntelliJ to make my change and forgot I had settings to organise imports and remove trailing whitespace, so that did introduce a bit of noise to the diff. Sorry! This project had no info on how to contribute so I just did the fix we needed for a local plugin build and am sending it all as one pull request.

Side note: while searching online to see if I was using that field wrong it seems the functionality of it has been regressed on more than one occasion.

 * https://issues.jenkins-ci.org/browse/JENKINS-24005 - You mention you fixed it in 1.0.10
 * https://issues.jenkins-ci.org/browse/JENKINS-24202 - Then again you fix it in 1.0.13

I don't think syncing a specific label/tag rather than head or changelist number is some obscure or strange use case so it doesn't fill me with confidence in this plugin that this option is so badly documented and gets broken on a seemingly regular basis. Especially when this plugin is the "Official Perforce" plugin for Jenkins. I know this is hard to unit test but if it can be I think it definitely should.

### CODE REVIEW

**Comment by Palmr** [comment]
Ah, cheers for the info @jenkinsadmin

**Comment by p4paul** [comment]
Hi Nick,

Thanks for looking at the 'Pin Build at Label' option.  The other email was automated from Jenkins, an interesting read for me too.

The original intention was to 'pin' the build to a label or change number for polling.  I had not intended to apply it to Build Now or Build Review.  The initial thinking was that 'Build Now' would always build the latest, but perhaps it does make sense to limit this to the 'pinned' label or change.

I'm reluctant to refactor the 'pin' to 'label' as it is an overused term in both Jenkins and Perforce, it also suggests it only works with labels when a change number could also be used. In addition, changing the name in Populate.java will impact the Job XML data causing data issues for all the current users.

I think the main fix is just in CheckoutTask.java:

+		// if label is specified via label in populate config then update
+		String populateLabel = populate.getLabel();
+		if (populateLabel != null && !populateLabel.isEmpty()) {
+			// Expand label with environment vars if one was defined
+			populateLabel = getWorkspace().expand(populateLabel, false);
+			try {
+				// if build is a change-number passed as a label
+				build = Integer.parseInt(populateLabel);
+			} catch (NumberFormatException e) {
+				build = populateLabel;
+			}
+		}
+

I would be happy to make this fix on your behalf or would you prefer to update your pull request?  If you do update the request please just include the CheckoutTask.java file and avoid the white space/import changes.

The regressions (24005 and 24202) are mainly due to issues/limitations around polling in Jenkins.  I know a lot of people like the polling functionality, but if you mix variable expansion ${var} etc... Jenkins has some limitations.  I would suggest using Perforce triggered builds.  Not only are they more efficient, but they can give you much better control.  Either use our free Swarm review tool, or make your own calls to the '/build/review' endpoint.

Thanks again for taking the time to look into this.

Kind regards,
Paul

> On 26 Mar 2015, at 11:14, Nick Palmer <notifications@github.com> wrote:
> 
> Recently changed from the other perforce plugin to this one and couldn't get it to sync a specific label.
> Saw the "Pin Build at Perforce Label" option and had no idea what that meant, but assumed it would sync on a given label. It did nothing however.
> 
> Grabbed the source and saw Populate.getPin() wasn't even referenced in CheckoutTask.java so now when calling getBuildChange() it checks for the label defined on the given populate config for the task.
> 
> As I could find no reference on "pinning" as terminology related to VCS labels and nobody I talked to could figure out what it meant with 100% confidence (even with the help text) I renamed the field to just "label", as that seemed to make sense to everyone in our company and matches the field in the other plugin. I could undo this however as I don't know how to make old config automatically change from pin -> label so any use of that field needs re-configuring in build tasks which is a pain for users now.
> 
> I used IntelliJ to make my change and forgot I had settings to organise imports and remove trailing whitespace, so that did introduce a bit of noise to the diff. Sorry! This project had no info on how to contribute so I just did the fix we needed for a local plugin build and am sending it all as one pull request.
> 
> Side note: while searching online to see if I was using that field wrong it seems the functionality of it has been regressed on more than one occasion.
> 
> 	• https://issues.jenkins-ci.org/browse/JENKINS-24005 - You mention you fixed it in 1.0.10
> 	• https://issues.jenkins-ci.org/browse/JENKINS-24202 - Then again you fix it in 1.0.13
> I don't think syncing a specific label/tag rather than head or changelist number is some obscure or strange use case so it doesn't fill me with confidence in this plugin that this option is so badly documented and gets broken on a seemingly regular basis. Especially when this plugin is the "Official Perforce" plugin for Jenkins. I know this is hard to unit test but if it can be I think it definitely should.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/jenkinsci/p4-plugin/pull/9
> 
> Commit Summary
> 
> 	• Changed Pin Label to Sync Label in populate options and made it have an effect
> File Changes
> 
> 	• M .gitignore (4)
> 	• M README.md (4)
> 	• M src/main/java/org/jenkinsci/plugins/p4/PerforceScm.java (57)
> 	• M src/main/java/org/jenkinsci/plugins/p4/populate/AutoCleanImpl.java (4)
> 	• M src/main/java/org/jenkinsci/plugins/p4/populate/ForceCleanImpl.java (6)
> 	• M src/main/java/org/jenkinsci/plugins/p4/populate/Populate.java (13)
> 	• M src/main/java/org/jenkinsci/plugins/p4/populate/PopulateDescriptor.java (12)
> 	• M src/main/java/org/jenkinsci/plugins/p4/populate/SyncOnlyImpl.java (6)
> 	• M src/main/java/org/jenkinsci/plugins/p4/tasks/CheckoutTask.java (25)
> 	• M src/main/java/org/jenkinsci/plugins/p4/tasks/PollTask.java (39)
> 	• M src/main/resources/org/jenkinsci/plugins/p4/populate/AutoCleanImpl/config.jelly (14)
> 	• R src/main/resources/org/jenkinsci/plugins/p4/populate/AutoCleanImpl/help-label.html (2)
> 	• M src/main/resources/org/jenkinsci/plugins/p4/populate/ForceCleanImpl/config.jelly (12)
> 	• R src/main/resources/org/jenkinsci/plugins/p4/populate/ForceCleanImpl/help-label.html (2)
> 	• M src/main/resources/org/jenkinsci/plugins/p4/populate/SyncOnlyImpl/config.jelly (12)
> 	• R src/main/resources/org/jenkinsci/plugins/p4/populate/SyncOnlyImpl/help-label.html (2)
> Patch Links:
> 
> 	• https://github.com/jenkinsci/p4-plugin/pull/9.patch
> 	• https://github.com/jenkinsci/p4-plugin/pull/9.diff
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by Palmr** [comment]
Thanks for the reply and the info @p4paul 

I'd be happy to re-do my change to just CheckoutTask.java's main fix, and set up my IDE nicely this time. This pull request came from a hacked up fork from yesterday I did to get our jenkins working again for our jobs, rather than the cleanest diff I could muster.
Also, I put my core fix at the end of that method so it overrides whatever might have been set earlier via ReviewProp.LABEL as we aren't using swarm or the review aspect of this plugin for this jenkins task. I should perhaps make the ReviewProp.LABEL setting override the Populate.getLabel() if it's set though, right?

Some background of our use case as we can't just build tips and call it a release for what we do:
We have a feature/dev -> main -> MajorRelease kind of branch structure. With a few MajorRelease branches. We mostly do fixes and enhancements on the release branch and merge down to main to spread it to other releases. Minor releases which we build/deploy are marked in the MajorRelease branch with a label on the revision of the file in that release.
When we do a release we have our changelists grouped up in a minor release job on the release branch, close that job, label all files at the revisions in those changelists on the job (using p4 tag), and then we have jenkins grab and build using file revisions with that label on it.
If a changelist in a job looks risky or hasn't been stable enough we just take it out of that job and move it to the next minor release job before doing a build.
This means we never build latest revisions on the release branch except via a polling job to check that all commits made actually compile and pass unit tests.

Our main goal is to be able to point to a workspace and grab all revision with a specific label and build that, knowing that only the labelled revisions were in the workspace.

**Comment by p4paul** [comment]
Hi Nick,

Thanks for offering to update the pull request.  I normally use Eclipse as it seemed to be favoured by the Community, but IntelliJ does seem to be on the up these days.  I doubt IntelliJ can read the Eclipse Formatting export XML file, but I would be happy to provide my settings if you think it would be useful.

I agree that letting the ReviewProp.LABEL take precedence does make sense.  I may need to double check the Matrix implementation as I forget exactly how the change is passed down to child builds.

Your build process is not that uncommon with the reliance on labels.  I have seen a similar setup with component builds being pinned by different label and build with multiple Jenkins Jobs then pulled together.  Out of interest what type of label are you using?  Automatic or Static label (i.e. do you set the Reviews: field or tag file revisions)?

Kind regards,
Paul

> On 26 Mar 2015, at 15:26, Nick Palmer <notifications@github.com> wrote:
> 
> Thanks for the reply and the info @p4paul
> 
> I'd be happy to re-do my change to just CheckoutTask.java's main fix, and set up my IDE nicely this time. This pull request came from a hacked up fork from yesterday I did to get our jenkins working again for our jobs, rather than the cleanest diff I could muster.
> Also, I put my core fix at the end of that method so it overrides whatever might have been set earlier via ReviewProp.LABEL as we aren't using swarm or the review aspect of this plugin for this jenkins task. I should perhaps make the ReviewProp.LABEL setting override the Populate.getLabel() if it's set though, right?
> 
> Some background of our use case as we can't just build tips and call it a release for what we do:
> We have a feature/dev -> main -> MajorRelease kind of branch structure. With a few MajorRelease branches. We mostly do fixes and enhancements on the release branch and merge down to main to spread it to other releases. Minor releases which we build/deploy are marked in the MajorRelease branch with a label on the revision of the file in that release.
> When we do a release we have our changelists grouped up in a minor release job on the release branch, close that job, label all files at the revisions in those changelists on the job (using p4 tag), and then we have jenkins grab and build using file revisions with that label on it.
> If a changelist in a job looks risky or hasn't been stable enough we just take it out of that job and move it to the next minor release job before doing a build.
> This means we never build latest revisions on the release branch except via a polling job to check that all commits made actually compile and pass unit tests.
> 
> Our main goal is to be able to point to a workspace and grab all revision with a specific label and build that, knowing that only the labelled revisions were in the workspace.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by Palmr** [comment]
Hey Paul,

Just had a go at undoing changes from yesterday and just applying the core fix. Though I'm not a git-person, more of a perforce guy, so somehow those commits just ended up in this pull request after I pushed to my fork...
Unit tests failed again somehow too...

If it's a total mess feel free to just close this pull request and implement the fix on your version!

We tag our files at revisions, so static labels I guess. We actually made a jenkins job to do this as perforce doesn't let you apply a label to the revisions of files in changelists in jobs. Here's the important bit from the shell task of our jenkins job:
```bash
# Assign label to previous build label
PREVIOUS_LABELLED_FILES=$(p4 files -e @$PREVIOUS_FOX_BUILD | sed -rn 's/^(.*?#[0-9]+) - .*$/\1/p')
for PREVIOUS_LABELLED_FILE in $PREVIOUS_LABELLED_FILES; do
  p4 tag -l $NEW_FOX_BUILD $PREVIOUS_LABELLED_FILE
done

# Assign label to head of files in each changelist (sorted from lowest to highest changelist earlier)
for CHANGELIST in $CHANGELISTS; do
  echo "Adding label to head of changelist: @$CHANGELIST"
  CHANGELIST_FILES=$(p4 describe -s $CHANGELIST | sed -rn 's/^... (\/\/Fox\/branches\/.*?)#[0-9]+.*$/\1/p')
  for CHANGELIST_FILE in $CHANGELIST_FILES; do
    p4 tag -l $NEW_FOX_BUILD $CHANGELIST_FILE@$CHANGELIST
  done
done
```
A little hacky perhaps, anything with bash/sed is bound to be, but it means our perforce repo is kept fairly clean with jobs holding the changelists that make one version different from another, and only one release branch holding multiple minor release revisions, possibly being worked on at the same time.

**Comment by p4paul** [comment]
Hi Nick,

I'm just adding you changes into the code base.  I tend to do most of my development in the Perforce Workshop and then copy the changes over to GitHub.

Here is a link to the Workshop, if you want to sign up and let me know your username I can add you to the project.

   https://swarm.workshop.perforce.com/projects/p4-jenkins/

The testPolling_Inc and testPolling_Pin were failing due to the order of precedence.  The Build Review uses two parameters ReviewProp.CHANGE and ReviewProp.LABEL, if set these must override the pinning option.

I have shelved your changes for review in the Workshop (login if you want to comment).

   https://swarm.workshop.perforce.com/reviews/12175/

If you want to sync the changes here are the Perforce details...

	P4PORT:		public.perforce.com:1666
	Depot Path:	//guest/perforce_software/p4jenkins/main/...

	Unshelve:	p4 unshelve -s 12174

Let me know if all looks good and I will submit the change and push it to GitHub.

Kind regards,
Paul


> On 26 Mar 2015, at 16:37, Nick Palmer <notifications@github.com> wrote:
> 
> Hey Paul,
> 
> Just had a go at undoing changes from yesterday and just applying the core fix. Though I'm not a git-person, more of a perforce guy, so somehow those commits just ended up in this pull request after I pushed to my fork...
> Unit tests failed again somehow too...
> 
> If it's a total mess feel free to just close this pull request and implement the fix on your version!
> 
> We tag our files at revisions, so static labels I guess. We actually made a jenkins job to do this as perforce doesn't let you apply a label to the revisions of files in changelists in jobs. Here's the important bit from the shell task of our jenkins job:
> 
> # Assign label to previous build label
> 
> PREVIOUS_LABELLED_FILES=
> $(p4 files -e @$PREVIOUS_FOX_BUILD | sed -rn 's/^(.*?#[0-9]+) - .*$/\1/p')
> for PREVIOUS_LABELLED_FILE in $PREVIOUS_LABELLED_FILES; do
> 
>   p4 tag -l 
> $NEW_FOX_BUILD $PREVIOUS_LABELLED_FILE
> done
> 
> 
> 
> # Assign label to head of files in each changelist (sorted from lowest to highest changelist earlier)
> for CHANGELIST in $CHANGELISTS; do
> 
>   
> echo "Adding label to head of changelist: @$CHANGELIST"
> 
>   CHANGELIST_FILES=
> $(p4 describe -s $CHANGELIST | sed -rn 's/^... (\/\/Fox\/branches\/.*?)#[0-9]+.*$/\1/p')
> 
>   
> for CHANGELIST_FILE in $CHANGELIST_FILES; do
> 
>     p4 tag -l 
> $NEW_FOX_BUILD $CHANGELIST_FILE@$CHANGELIST
> 
>   
> done
> done
> A little hacky perhaps, anything with bash/sed is bound to be, but it means our perforce repo is kept fairly clean with jobs holding the changelists that make one version different from another, and only one release branch holding multiple minor release revisions, possibly being worked on at the same time.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by Palmr** [comment]
Hey Paul,

I'd never heard of Perforce Workshop before, so signed up there with the same username, palmr.

Changes look good to me, and definitely less breaking than mine!

Cheers,
Nick

**Comment by p4paul** [comment]
I have added you as a member, so you should be able to comment and shelve changes for review.  Just remember to include a #review tag in the Shelve description.

I'll submit your change with a @palmr tag, you should be able to access the SNAPSHOT build soon after.

BTW:  Which company do you work for?  If you want to send my your work address (pallen@perforce.com) I'll see if our Marketing team can send you some swag.

Kind regards,
Paul


> On 27 Mar 2015, at 10:46, Nick Palmer <notifications@github.com> wrote:
> 
> Hey Paul,
> 
> I'd never heard of Perforce Workshop before, so signed up there with the same username, palmr.
> 
> Changes look good to me, and definitely less breaking than mine!
> 
> Cheers,
> Nick
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Pull request closed without merging**
