### PR TITLE
Fix polling on workflow jobs.  (JENKINS-29598)

### PR DESCRIPTION
**Pull request by rpk2msu**

### CODE REVIEW

**Comment by rpk2msu** [comment]
I messed up an included both mine and Prathap's change in the single pull request.  We were intending to submit both, but individually.  Let me know if you'd rather they been treated independently and we can resubmit.

**Comment by pyssling** [comment]
Any chance of getting this released soon? Would really appreciate having this working...

**Comment by p4paul** [comment]
I have been out on vacation, so hopefully this week. After that I'm out of the office travelling for three weeks, but will have my laptop.

**Comment by pyssling** [comment]
Thank you, it is all very much appreciated. Cheers.

**Comment by philmcardle** [comment]
I don't know whether to report this in JIRA as yet, as I'm using a snapshot build (3ed55a46...) in order to get this functionality, but, when I change the p4sync step in the pipeline script, the polling does not change - it continues to poll using the old settings, as seen in job/myJob/scmPollLog/ and job/myJob/XX/pollingLog/ - the output and action of the actual sync step when ran by workflow is correct.

Tried disabling and re-enabling 'Poll SCM' in the UI to no effect. Will report it in JIRA if I can reproduce it on a released 1.3.8

**Comment by p4paul** [comment]
The release is out: http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/p4/
However, it can take 6hours or more for it to reach the update centre.

**Comment by rpk2msu** [comment]
That's great Paul!

Phil, I believe that what you're seeing is an expected behavior of the pipeline plugin.  It identifies the set of VCSs used as part of the build when running a build and then uses that baseline for polling going forward.  To initially create a baseline (or re-baseline), I believe you need to complete a build (either manually or due to existing triggering/polling).

**Comment by philmcardle** [comment]
Thanks Rick - looks like possibly any successful build whether by polling or manually initiated will change it. My script earlier was failing every time (albeit intentionally). Makes sense.

On a similar topic, and I know isn't an ideal place to ask questions, but, should the p4sync step support the poll:false option listed here? https://github.com/jenkinsci/workflow-plugin/blob/master/scm-step/README.md

It seems to support changelog:false, but setting up two p4sync statements, one with poll:false on a brand new job with 'Poll SCM' enabled still polls both.

Although, I don't actually need this, so I should maybe stop looking at it :)

**Comment by rpk2msu** [comment]
I know that I'm unlikely to be able to look at anything soon.  Probably the best thing to do is to create a separate JIRA with that behavior explained, while also pointing out the lack of use-case currently to help make clear the priority of working on it.

**Pull request merged**
