### PR TITLE
Add additional catch for NoSuchFileException next to FileNotFoundException

### PR DESCRIPTION
**Pull request by Sigma-Erebus**
Since in some cases, the rm -rf command has recently started returning NoSuchFileExceptions instead of FileNotFoundExceptions, it treats them as a failure due to not having a catch for them, even though their functionality in this case should be identical.

In a Jenkins pipeline, it recently stopped correctly executing the p4sync command. Stating reason for failure NoSuchFileException issued by an 'rm -rf {folder}' command.
after that it prints some text and tries to remove the folder in an alternate way but fails once more due to the folder never having existed in the first place.
through this printed text I've been able to find the code that tries the 'rm -rf {folder}' command, and noticed that it does have a check for a FileNotFoundException (which I've seen get raised in past but getting ignored by the catch clause).

So all I've done is add a second catch clause that catches and ignores the NoSuchFileException in the same way that FileNotFoundException gets ignored.
So that it won't continue into the IOException to attempt a different method of removing said directory.

Since I'm much more familiar with the ways of Perforce personally, I'm not very sure how git works with pull requests and such, and java code is also new to me, so I'm unsure how to approach the testing properly.
I completely understand if that is enough to have this pull request denied, and if so, please give me some pointers as to how I could go through the correct steps to meet the requirements of having this pull request approved :)

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by kjs104901** [comment]
I wrote my guess on Jenkins Jira.
https://issues.jenkins.io/browse/JENKINS-72098
I think the problem is 'FileUtils.forceDelete' raises 'java.io.IOException: DOS or POSIX file operations not available for'

> 
> 
> Guess they decided to delete workspace by themselves with 'deleteRecursive()'
> 
> https://github.com/jenkinsci/pipeline-groovy-lib-plugin/commit/76ad53e052aa7b9a7d0101b23e83a8ed5ab43feb
> 
> And p4 plugin fallback is wrong on Windows.
> 
> FileUtils.forceDelete raise exception IOException but not FileNotFoundException on Windows
> 
> java.io.IOException: DOS or POSIX file operations not available for
> 
> And in the catch block, 'Paths.get(root)' raises java.nio.file.NoSuchFileException, so silentlyForceDelete fails.
> 
> https://github.com/jenkinsci/p4-plugin/blob/581e72229e106680b514b4cbe6c89225ccab0f5a/src/main/java/org/jenkinsci/plugins/p4/client/ClientHelper.java#L493C30-L493C30
> 
> 
> In the catch block, the plugin must check if the path or file exists.
> And if not, it must return true.
> 
> 
> Try below in Jenkins script console on Windows
> 
> 
> ```
> import org.apache.commons.io.FileUtils;
> import java.nio.file.Path;
> import java.nio.file.Paths;
> import java.nio.file.Files;
> 
> def root = "D:\\JenkinsStage\\.jenkins\\workspace\\TestBuild@libs\\df22c977f0a70bd7e2b7eedfec61e8da94ef69d6cddd1103fd8ff1afe8f7844a";
> 
> try {
>   FileUtils.forceDelete(new File(root));
> } catch (FileNotFoundException ignored) {
>   // ignore
> } catch (IOException alt) {
>   println("Unable to delete, trying alternative method... " + alt.getLocalizedMessage());
>   
>   List<Path> pathsToDelete = Files.walk(Paths.get(root))
>     .sorted(Comparator.reverseOrder())
>     .collect(Collectors.toList());
>   boolean success = true;
>   for (Path path : pathsToDelete) {
>     try {
>       path.toFile().setWritable(true);
>       Files.deleteIfExists(path);
>     } catch (IOException e) {
>       println("Unable to delete path: " + path + " error: " + e.getLocalizedMessage());
>       success = false;
>     }
>   }
>   
>   if (!success) {
>     throw new IOException("Unable to delete all files (see log for details).");
>   }
> }
> ```
> 
>

**Comment by Sigma-Erebus** [comment]
Yeah, checking if the folder exists in the first place would also work, since it skips the attempted delete right away

**Comment by kjs104901** [comment]
I'll make a pull request for this.

Catching NoSuchFileException won't help cause forceDelete never throw it.
https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FileUtils.html#forceDelete(java.io.File)

It feels like
throwing java.io.IOException when the file not exists on Windows is bug

image

**Comment by kjs104901** [comment]
Just made a pull request.
https://github.com/jenkinsci/p4-plugin/pull/194

**Comment by kjs104901** [comment]
@Sigma-Erebus 

You can see '**Unable to delete, trying alternative method**' in your log.
That means the exception thrown by '**forceDelete**' has been caught by '**catch (IOException alt)**'

Then '**NoSuchFileException**' will be throwed from the very next line '**Files.walk(Paths.get(root))**',
while attempting to traverse a non-existent folder.

**Comment by Sigma-Erebus** [comment]
Ahhh yep, reading through the code again that makes total sense, I was being a dumdum...

**Pull request closed without merging**
