### PR TITLE
JENKINS-56248: P4Plugin Polls Workspaces With Disabled Polling (poll: false)

### PR DESCRIPTION
**Pull request by lystor**
Fix for https://issues.jenkins-ci.org/browse/JENKINS-56248

### CODE REVIEW

**Comment by p4paul** [comment]
I have written a test for this issue, but your fix did not seem to work for the following script:
```
pipeline {
  agent any
  options {
    skipDefaultCheckout(true)
  }
  stages {
    stage('A') {
      steps {
        checkout poll: true, scm: perforce(
          credential: 'CREDENTIAL', 
          populate: forceClean(quiet: true),
          workspace: manualSpec(name: 'jenkins-${NODE_NAME}-${JOB_NAME}-${EXECUTOR_NUMBER}-A', 
            spec: clientSpec(view: '//depot/main/A/... //${P4_CLIENT}/A/...')))
      }
    }
    stage('B') {
      steps {
        checkout poll: false, scm: perforce(
          credential: 'CREDENTIAL', 
          populate: forceClean(quiet: true),
          workspace: manualSpec(name: 'jenkins-${NODE_NAME}-${JOB_NAME}-${EXECUTOR_NUMBER}-B', 
            spec: clientSpec(view: '//depot/main/B/... //${P4_CLIENT}/B/...')))
      }
    }
  }
}
```

I'll take another look, but I have a feeling there might be a Jenkins bug here.

**Comment by p4paul** [comment]
The test case: https://gist.github.com/p4paul/3d795cf8fbdd1ff1651dc34ceea6a804#file-pollingtest

**Comment by lystor** [comment]
Hi paul,

Jenkins polls workspaces not only if poll == true but also if changelog == true (default value).

I tested your example with changelog: false and provided patch on Jenkins 2.164.1 it works for me:

```
pipeline {
    agent {
        node {
            label("k02-bld-win-03")
        }
    }

    options {
        skipDefaultCheckout(true)
    }

    triggers {
        pollSCM("* * * * *")
    }

    stages {
        stage('A') {
            steps {
                checkout poll: true, changelog: true, scm: perforce(
                        credential: 'perforce-ticket-jenkins',
                        populate: forceClean(quiet: true),
                        workspace: manualSpec(name: 'jenkins-${NODE_NAME}-${JOB_NAME}-${EXECUTOR_NUMBER}-A',
                                spec: clientSpec(view: '//playground/jenkins-main/A/... //${P4_CLIENT}/A/...')))
            }
        }
        stage('B') {
            steps {
                checkout poll: false, changelog: false, scm: perforce(
                        credential: 'perforce-ticket-jenkins',
                        populate: forceClean(quiet: true),
                        workspace: manualSpec(name: 'jenkins-${NODE_NAME}-${JOB_NAME}-${EXECUTOR_NUMBER}-B',
                                spec: clientSpec(view: '//playground/jenkins-main/B/... //${P4_CLIENT}/B/...')))
            }
        }
    }
}
```

Perforce Software Polling Log
```
Started on Apr 10, 2019 1:04:00 PM
P4: Polling on: master with:jenkins-master-test1-0-A
Found last change 1197811 on syncID jenkins-NODE_NAME-test1-EXECUTOR_NUMBER-A
... p4 client -o jenkins-master-test1-0-A +
... p4 info +
... p4 info +
... p4 client -o jenkins-master-test1-0-A +

        P4 Task: establishing connection.
... server: perforce:1666
... node: k02-jenkins
P4: Polling with range: 1197811,now
... p4 changes -m20 //jenkins-master-test1-0-A/...@1197811,now +
... p4 repos -C +
        no polling baseline in C:\jenkins\workspace\test1 on k02-bld-win-03
Done. Took 56 ms
No changes
```

**Comment by p4paul** [comment]
Jenkins 2.164.1 would explain it.  All the automated tests run on the oldest supported version 2.89.1 - I might need to bump the min version.

**Comment by lystor** [comment]
> I might need to bump the min version.

Good idea.
Thank you

**Comment by p4paul** [comment]
The Key built for StreamWorkspaceImpl may not be unique if the StreamName is used on its own.  It is likely that the same Stream name would be used in other specs.

**Pull request merged**
