### PR TITLE
[Jenkins-45657] Recreation of pull request

### PR DESCRIPTION
**Pull request by fbyrne**

### CODE REVIEW

**Comment by fbyrne** [comment]
From Previous:
Hi Fergus,

Thank you for the Pull Request. I have been giving this area some thought as the feature is relatively new and not all the use cases have been captured.

The BranchesScmSource use p4 dirs to find branch candidates from the list ofInclude branches then looks for a Jenkinsfile at the root of each branch. You could use a p4 dirs search pattern in the Include branches list (e.g. //depot/*/components). Currently the plugin strips any trailing ... and adds a /* to the end of the path, which may not be that helpful (see cleanDirPaths). The directory name at the end of each path then becomes the branch name.

e.g. given a p4 dirs of //depot/projA/* you get two branches main and r1.0:

//depot/projA/main/ --> 'main'
//depot/projA/r1.0/ --> 'r1.0'
This may not suit all users as the last directory name may not be a suitable branch name.

e.g. a p4 dirs of //depot/projA/*/components/* would clash with the branch names:

//depot/projA/main/components/a --> 'a'
//depot/projA/r1.0/components/a --> 'a'
//depot/projA/main/components/b --> 'b'
//depot/projA/r1.0/components/b --> 'b'
Perhaps a group matcher with a regex?

e.g. //depot/projA/(.*)/components/(.*) and a name builder {$2}-{$1} giving:

//depot/projA/main/components/a --> 'a-main'
//depot/projA/r1.0/components/a --> 'a-r1.0'
//depot/projA/main/components/b --> 'b-main'
//depot/projA/r1.0/components/b --> 'b-r1.0'
In addition the subsequent search for a Jenkinsfile may not suit all users as some change the name or store it in a non-root locations (e.g. scripts/).

**Comment by fbyrne** [comment]
Happy to merge in the changes, but please can you update the following:

 BranchesScmSource: change the display name back to Helix Branches as Source seemed a bit vague.
 Please revert P4EnvironmentContributor and PerforceScmSourceTest as there are no code changes just white space.

**Comment by fbyrne** [comment]
Hi Paul, 

I had made a mess of the previous pull request because I rebased between the fixes.

I have created a new PR with the changes above.

On your point about branch selection.  I chose not to change drastically the existing source definition.

There is no standard branching model in perforce.  The company I work for use perforce as its main SCM.    We have hundreds/thousands of branches under a common base.  

1. The current plugin adds '/*' and performs a dir to list branches:
- An option to explicitly define only the needed branches would be useful here.
- In my case I know exactly the branches I need.  This changes infrequently and I don't want to keep all old branches in the view.
- So a wildcard option is not great in this context.

2. Using dirs to retrieve branches
- This is a good option however the performance of dirs with wildcards is poor.
- For example given a general branch convention of //depot/<version>.dev.<id>.<name>
- The command would be p4 dirs //depot/<version>.dev.*.blah*
- In my case with thousands of branches, it takes several minutes to complete.
- Whereas p4 dirs //depot/* returns instantly

3. So my choice was based on performance and minimal changes.  The regex seemed to fit the best.

Happy to help where I can.  
Regards,
Fergus

**Comment by p4paul** [comment]
I think you might be missing the Jelly script?

**Comment by fbyrne** [comment]
yep, good spot.  ill submit that tomorrow.

**Pull request merged**
