### PR TITLE
Fix JENKINS-28760: Set line endings explicitly for template workspaces

### PR DESCRIPTION
**Pull request by matthauck**
This fixes the issue for me both in instances of creating a new workspace from a template, and in updating a previously-created workspace from a template.

### CODE REVIEW

**Comment by p4paul** [comment]
I have merged your fix, but there must be a bug in p4java as the LineEnding option should be copied from the template.

**Comment by matthauck** [comment]
Yeah, it looks like it was depending on the p4java code to copy all the fields. Thanks for merging this change. 

Any chance to get a new release soon with this change in? =)

**Comment by p4paul** [comment]
Hi Matt,

Hopefully this week (possibly today).  Just testing the latest p4java 15.1 release in Jenkins.

Kind regards,
Paul

> On 8 Jun 2015, at 05:31, Matt Hauck <notifications@github.com> wrote:
> 
> Yeah, it looks like it was depending on the p4java code to copy all the fields. Thanks for merging this change.
> 
> Any chance to get a new release soon with this change in? =)
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by matthauck** [comment]
sweet. saw the update today and upgraded. Thanks!

**Pull request merged**
